services:
  server:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    user: node
    working_dir: /home/node/app/
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ./:/home/node/app/
    ports:
      - 3000:3000
