services:
  server:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    user: node
    working_dir: /home/node/app/
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ./:/home/node/app/
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
  stockfish:
    image: audio-engineer/chess-teacher-stockfish:latest
    ports:
      - 8000:8000
  firebase:
    image: firebase-emulator:latest
    ports:
      - 9000:9000
      - 9099:9099
      - 4000:4000
