services:
  server:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    user: node
    working_dir: /home/node/$COMPOSE_PROJECT_NAME
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ./:/home/node/$COMPOSE_PROJECT_NAME
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
  stockfish:
    image: audio-engineer/chess-teacher-stockfish:latest
    ports:
      - 8000:8000
