services:
  server:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    user: node
    working_dir: /home/node/$COMPOSE_PROJECT_NAME
    environment:
      - NODE_ENV=development
    tty: true
    volumes:
      - ./:/home/node/$COMPOSE_PROJECT_NAME
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
  firebase:
    image: audio-engineer/chess-teacher-firebase:latest
    build: https://github.com/audio-engineer/chess-teacher-firebase.git
    ports:
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 9000:9000
      - 9099:9099
  stockfish:
    image: audio-engineer/chess-teacher-stockfish:latest
    build: https://github.com/audio-engineer/chess-teacher-stockfish.git
    ports:
      - 8000:8000
